variables:
  needToUpdateAppImage: true
  needToUpdateDatabase: true
  needToRunUnitTests: true
  needToRunIntegrationTests: true
  needToRunAcceptanceTests: true

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - Assignment

pool: 
  vmImage: ubuntu-latest

stages:
  - template: deploy-api-service.yml
    parameters:
      serviceName: 'Assignment'