variables:
  needToUpdateAppImage: false
  needToUpdateDatabase: false
  needToRunUnitTests: false
  needToRunIntegrationTests: false
  needToRunAcceptanceTests: false

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - Assignment

pool: 
  vmImage: ubuntu-latest

stages:
  - template: ../pipeline/deploy-api-service.yml
    parameters:
      serviceName: 'Assignment'