variables:
  needToUpdateAppImage: false

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - Outbox.Job

pool: 
  vmImage: ubuntu-latest

stages:
  - template: ../pipeline/outbox-job.yml
    parameters:
      serviceName: 'assignment-outbox-job'