kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.serviceName }}
  labels:
    app.kubernetes.io/name: {{ .Values.serviceName }}
    app.kubernetes.io/part-of: 'authorization'
spec:
  replicas: 1
  strategy:
   type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.serviceName }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.serviceName }}
        app.kubernetes.io/part-of: 'authorization'
    spec:
      imagePullSecrets:
      - name: secret
      containers:
      - name: {{ .Values.serviceName }}
        image: pvauthorizationcr.azurecr.io/{{ .Values.serviceName }}:1.0.0
        imagePullPolicy: Always
        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: "DEV"