variables:
  needToUpdateAppImage: true

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - Inbox.Job

pool: 
  vmImage: ubuntu-latest

stages:
  - template: ../pipeline/inbox-job.yml
    parameters:
      serviceName: 'authorization-inbox-job'