variables:
  needToUpdateAppImage: true

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - IdentityServer

pool: 
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: 'Build'
    jobs:
      - job: Build
        displayName: 'Build and publish artifacts'
        steps:
        - template: ../pipeline/publish-manifests-artifact.yml
          parameters:
            manifestsFolder: 'IdentityServer/src/IdentityServer/pipeline'

        - template: ../pipeline/build-host-and-publish-artifact.yml
          parameters:
            hostProject: 'IdentityServer/src/IdentityServer/IdentityServer.csproj'
            hostName: 'IdentityServer'
            acrRepository: 'identity-server'

  - stage: deploy_dev
    displayName: 'Deploy DEV'
    jobs:
    - deployment: Deploy
      displayName: Deploy
      environment: 'DEV'
      strategy: 
        runOnce:
          deploy:
            steps:
            - download: none

            - template: ../pipeline/deploy-host-artifact-to-app-service.yml
              parameters:
                appServiceName: 'pv-identity-server'
                hostName: 'IdentityServer'