variables:
  needToUpdateAppImage: true

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - IdentityServer

pool: 
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: 'Build'
    variables:
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'
      dotNetFramework: 'net6.0'
      targetRuntime: 'linux-x64'
      projects: 'IdentityServer/**/*.csproj'
    jobs:
      - job: Build
        displayName: 'Build and publish artifacts'
        steps:
        - template: publish-manifests-artifact.yml
          parameters:
            manifestsFolder: 'IdentityServer/src/IdentityServer/pipeline'

        - template: build-and-push-acr-image.yml
          parameters:
            hostProject: 'IdentityServer/src/IdentityServer/IdentityServer.csproj'
            hostName: 'IdentityServer'
            acrRepository: 'identity-server'

  - stage: deploy_dev
    displayName: 'Deploy DEV'
    jobs:
    - deployment: Deploy
      displayName: Deploy
      environment: 'DEV'
      strategy: 
        runOnce:
          deploy:
            steps:
            - download: none

            - template: deploy-acr-image-to-aks.yml
              parameters:
                acrRepository: 'identity-server'