variables:
  needToUpdateAppImage: true

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - IdentityServer

pool: 
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: 'Build'
    jobs:
      - job: Build
        displayName: 'Build and publish artifacts'
        steps:
        - template: pipeline\publish-manifests-artifact.yml@authorization
          parameters:
            manifestsFolder: 'IdentityServer/src/IdentityServer/pipeline'

        - template: pipeline\build-and-push-acr-image.yml@authorization
          parameters:
            hostProject: 'IdentityServer/src/IdentityServer/IdentityServer.csproj'
            hostName: 'IdentityServer'
            acrRepository: 'identity-server'

  - stage: deploy_dev
    displayName: 'Deploy DEV'
    jobs:
    - deployment: Deploy
      displayName: Deploy
      environment: 'DEV'
      strategy: 
        runOnce:
          deploy:
            steps:
            - download: none

            - template: pipeline\deploy-acr-image-to-aks.yml@authorization
              parameters:
                acrRepository: 'identity-server'