trigger:
  branches:
    include:
    - main
  paths:
    include:
    - IdentityServer

pool: 
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: 'Build'
    variables:
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'
      dotNetFramework: 'net6.0'
      targetRuntime: 'linux-x64'
      projects: 'IdentityServer/**/*.csproj'
    jobs:
      - job: Build
        displayName: 'Build and publish artifacts'
        steps:
        - template: publish-manifests-artifact.yml
          parameters:
            manifestsFolder: 'IdentityServer/src/IdentityServer/pipeline'