kind: Service
apiVersion: v1
metadata:
  name: role-api
  labels:
    app.kubernetes.io/name: 'role-api'
    app.kubernetes.io/part-of: 'authorization'
spec:
  selector:
    app.kubernetes.io/name: role-api
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80