kind: Service
apiVersion: v1
metadata:
  name: role-api
  labels:
    app.kubernetes.io/name: 'role-api'
    app.kubernetes.io/part-of: 'authorization'
spec:
  selector:
    app.kubernetes.io/name: role-api
  type: NodePort
  ports:
  - name: api
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 8081
  - name: grpc
    protocol: TCP
    port: 8080
    targetPort: 8080