# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - Role

pool: 
  vmImage: ubuntu-latest

variables:
  solution: 'Role/Role.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '-r $(runtimeIdentifier) /p:RestoreUseSkipNonexistentTargets=false'

- task: DotNetCoreCLI@2
  displayName: 'Unit tests'
  inputs:
    command: test
    projects: 'Role/tests/unit/*/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Integration tests'
  inputs:
    command: test
    projects: 'Role/tests/integration/*/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
