trigger: none

pool: 
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  project: 'Authorization/src/Authorization.SDK/Authorization.SDK.csproj'

steps:
- task: NuGetToolInstaller@1

- task: DotNetCoreCLI@2
  displayName: 'Nuget restore'
  inputs:
    command: restore
    projects: $(project)
    feedsToUse: 'select'
    vstsFeed: 'Authorization/authorizationFeed'
    includeNuGetOrg: true      

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
    projects: $(project)

- task: DotNetCoreCLI@2
  displayName: "Pack" 
  inputs:
    command: 'pack'
    nobuild: true
    projects: $(project)
    arguments: '--no-build'

- task: NuGetCommand@2
  displayName: 'Nuget Push'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    publishVstsFeed: 'Authorization/authorizationFeed'
    versioningScheme: 'off'
    allowPackageConflicts: true
