trigger: none

pool: 
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  project: 'Common/src/Common.Infrastructure/Common.Infrastructure.csproj'

steps:
- task: NuGetToolInstaller@1

- task: DotNetCoreCLI@2
  displayName: 'Nuget restore'
  inputs:
    command: restore
    projects: $(project)
    feedsToUse: 'select'
    vstsFeed: 'Authorization/authorizationFeed'
    includeNuGetOrg: true      

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
    projects: $(project)

- task: NuGetCommand@2
  displayName: 'Nuget Pack'
  inputs:
    command: pack
    packagesToPack: $(project)

- task: NuGetCommand@2
  displayName: 'Nuget Push'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    publishVstsFeed: 'Authorization/authorizationFeed'
    versioningScheme: 'off'
    allowPackageConflicts: true
