trigger: none

pool: 
  vmImage: ubuntu-latest

steps:
  - task: NuGetCommand@2
    inputs:
    command: pack
    packagesToPack: 'Common/src/Common.Domain/Common.Domain.csproj1'
    packDestination: '$(Build.ArtifactStagingDirectory)'

