trigger: none

pool: 
  vmImage: ubuntu-latest

- task: NuGetCommand@2
  inputs:
    command: pack
    packagesToPack: 'Common/src/Common.Domain/Common.Domain.csproj'
    packDestination: '$(Build.ArtifactStagingDirectory)'

