trigger: none

pool: 
  vmImage: ubuntu-latest

steps:
- task: NuGetCommand@2
  displayName: 'Nuget Pack'
  inputs:
    command: pack
    packagesToPack: 'Common/src/Common.Domain/Common.Domain.csproj'

- task: NuGetCommand@2
  displayName: 'Nuget Push'
  inputs:
    command: 'push'
    feedsToUse: 'select'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'authorizationFeed'
    versioningScheme: 'off'
    allowPackageConflicts: true
