kind: Deployment
apiVersion: apps/v1
metadata:
  name: identity-server
  labels:
    app.kubernetes.io/name: 'identity-server'
    app.kubernetes.io/part-of: 'authorization'
spec:
  replicas: 1
  strategy:
   type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: identity-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: 'identity-server'
        app.kubernetes.io/part-of: 'authorization'
    spec:
      containers:
      - name: identity-server
        image: pvauthorizationcr.azurecr.io/identity-server:1.0.0
        imagePullPolicy: Always
        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: "DEV"
      restartPolicy: Always
      dnsPolicy: Default