variables:
  needToUpdateAppImage: true
  needToUpdateDatabase: false

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - pipeline/ingress

pool: 
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: 'Build'
    jobs:

      - job: Manifest
        displayName: 'Publish Manifest Artifact'
        steps:
          - task: CopyFiles@2
            displayName: 'Copy Manifest'
            inputs:
              SourceFolder: 'pipeline/ingress'
              Contents: ingress.yml
              TargetFolder: '$(Build.ArtifactStagingDirectory)/manifest'
         
          - task: PublishPipelineArtifact@1
            displayName: 'Publish Manifest Artifact'
            inputs:
              targetPath: $(build.artifactStagingDirectory)/manifest
              artifact: 'manifestDrop'
              publishLocation: 'pipeline'

  - stage: deploy_dev
    displayName: 'Deploy DEV'
    jobs:
    
    - deployment: Deploy
      displayName: Deploy
      environment: 'DEV'
      strategy: 
        runOnce:
          deploy:
            steps:
            - download: none

            - task: DownloadPipelineArtifact@2
              inputs:
                artifactName: 'manifestDrop'
                targetPath: '$(System.ArtifactsDirectory)/manifest'
            
            - task: KubernetesManifest@0
              displayName: Create imagePullSecret
              inputs:
                action: createSecret
                namespace: default
                secretName: secret
                dockerRegistryEndpoint: pvauthorizationcr-sc
                kubernetesServiceConnection: pvauthorizationaks-sc
            
            - task: KubernetesManifest@0
              displayName: Deploy to Kubernetes cluster
              inputs:
                action: deploy
                namespace: default
                manifests: $(System.ArtifactsDirectory)/manifest/ingress.yml
                imagePullSecrets: |
                  secret
                kubernetesServiceConnection: pvauthorizationaks-sc