variables:
  needToUpdateAppImage: false
  needToUpdateDatabase: false
  needToRunAcceptanceTests: true

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - Authorization

pool: 
  vmImage: ubuntu-latest

stages:
  - template: ../pipeline/deploy-api-service.yml
    parameters:
      serviceName: 'Authorization'