variables:
  needToUpdateAppImage: true
  needToUpdateDatabase: false

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - Authorization

pool: 
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: 'Build'
    jobs:

      - job: Manifest
        displayName: 'Publish Manifest Artifact'
        steps:
        - template: ../pipeline/publish-manifests-artifact.yml
          parameters:
            manifestsFolder: 'Authorization/src/Authorization.Host.API/pipeline'

      - job: BuildHost
        displayName: 'Build and push image to ACR'
        condition: and(succeeded(), eq(variables.needToUpdateAppImage, 'true'))
        steps:

        - template: ../pipeline/build-host-and-push-acr-image.yml
          parameters:
            hostProject: 'Authorization/src/Authorization.Host.API/Authorization.Host.API.csproj'
            hostName: 'Authorization.Host.API'
            acrRepository: 'authorization-api'

      - job: BuildDatabase
        displayName: 'Build Database and publish artifact'
        condition: and(succeeded(), eq(variables.needToUpdateDatabase, 'true'))
        steps:
        - template: ../pipeline/build-database-and-publish-artifact.yml
          parameters:
            dbProjectPath: 'Authorization/src/Authorization.Database/Build.Authorization.Database.csproj'
            dacpacFolder: 'Authorization/src/Authorization.Database/bin/Release/netstandard2.0'
            dacpacName: 'Build.Authorization.Database.dacpac'

  - stage: deploy_dev
    displayName: 'Deploy DEV'
    jobs:

    - job: publishDB
      displayName: 'Publish Database'
      condition: and(succeeded(), eq(variables.needToUpdateDatabase, 'true'))
      pool: 
        vmImage: 'windows-latest'
      steps:
        - checkout: none

        - template: ../pipeline/deploy-database.yml
          parameters:
            dbName: 'authorization'
            dacpacFileName: 'Build.Authorization.Database.dacpac'
    
    - deployment: Deploy
      displayName: Deploy
      environment: 'DEV'
      dependsOn: publishDB
      condition: and(not(canceled()), in(dependencies.publishDB.result, 'Succeeded', 'Skipped'))
      strategy: 
        runOnce:
          deploy:
            steps:
            - download: none

            - template: ../pipeline/deploy-acr-image-to-aks.yml
              parameters:
                acrRepository: 'authorization'
                serviceName: 'authorization-api'