kind: Deployment
apiVersion: apps/v1
metadata:
  name: authorization-inbox-job
  labels:
    app.kubernetes.io/name: 'authorization-inbox-job'
    app.kubernetes.io/part-of: 'authorization'
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: authorization-inbox-job
  template:
    metadata:
      labels:
        app.kubernetes.io/name: 'authorization-inbox-job'
        app.kubernetes.io/part-of: 'authorization'
    spec:
      containers:
      - name: authorization-inbox-job
        image: pvauthorizationcr.azurecr.io/inbox-job:1.0.0
        imagePullPolicy: Always
        env:
        - name: KeyVaultName
          value: 'pv-authorization-kv'
        - name: PubSub__EventProcessingServiceName
          value: 'authorization-api'
        - name: PubSub__Events__0
          value: Role.SDK.Events.RoleCreatedEvent
        - name: PubSub__Events__1
          value: Role.SDK.Events.RoleRenamedEvent
        - name: PubSub__Events__2
          value: Role.SDK.Events.RolePermissionsChangedEvent
        - name: PubSub__Events__3
          value: Role.SDK.Events.RoleDeletedEvent
        - name: PubSub__Events__4
          value: Assignment.SDK.Events.AssignmentEvent
        - name: PubSub__Events__5
          value: Assignment.SDK.Events.DeassignmentEvent
        - name: PubSub__Events__6
          value: Role.SDK.Events.PermissionCreatedEvent
        - name: PubSub__Events__7
          value: Role.SDK.Events.PermissionDeletedEvent
        - name: SERVICE__authorization-api__grpc__HOST
          value: 'authorization-api'
        - name: SERVICE__authorization-api__grpc__PORT
          value: '8080'