kind: Deployment
apiVersion: apps/v1
metadata:
  name: assignment-api
  labels:
    app.kubernetes.io/name: 'assignment-api'
    app.kubernetes.io/part-of: 'authorization'
spec:
  replicas: 1
  strategy:
   type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: assignment-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: 'assignment-api'
        app.kubernetes.io/part-of: 'authorization'
    spec:
      containers:
      - name: assignment-api
        image: pvauthorizationcr.azurecr.io/assignment-api:1.0.0
        imagePullPolicy: Always
        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: "DEV"