kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.jobService }}-{{ .Values.jobType }}-job
  labels:
    app.kubernetes.io/name: '{{ .Values.jobService }}-{{ .Values.jobType }}-job'
    app.kubernetes.io/part-of: 'authorization'
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.jobService }}-{{ .Values.jobType }}-job
  template:
    metadata:
      labels:
        app.kubernetes.io/name: '{{ .Values.jobService }}-{{ .Values.jobType }}-job'
        app.kubernetes.io/part-of: 'authorization'
    spec:
      containers:
      - name: assignment-outbox-job
        image: pvauthorizationcr.azurecr.io/{{ .Values.jobType }}-job:1.0.0
        imagePullPolicy: Always
        env:
        - name: KeyVaultName
          value: 'pv-{{ .Values.jobService }}-kv'