kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.jobService }}-{{ .Values.jobType }}-job
  labels:
    app.kubernetes.io/name: '{{ .Values.jobService }}-{{ .Values.jobType }}-job'
    app.kubernetes.io/part-of: 'authorization'
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.jobService }}-{{ .Values.jobType }}-job
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80